#!/usr/bin/env bash
cat .dotfilesrc | while read -r src dest; do
    eval src=$PWD/$src
    eval dest=$dest

    if [ -z $dest ]; then
        continue
    fi

    if [ -e "$dest" ]; then
        echo "Creating backup copy for $dest"$
        mkdir -p "$HOME/.tmp"
        mv -t "$HOME/.tmp" "$dest"
    fi

    echo "$src -> $dest"
    ln -s $src $dest
done
