set nocompatible
set encoding=utf-8

if isdirectory(expand('~/.vim/bundle/Vundle.vim/'))
    filetype off

    set rtp+=~/.vim/bundle/Vundle.vim/
    call vundle#rc()

    Plugin 'gmarik/Vundle.vim'
    Plugin 'endel/vim-github-colorscheme'
    Plugin 'ap/vim-buftabline'

    filetype plugin indent on
endif

try
    colorscheme github
catch
    colorscheme desert
endtry

try
    let g:buftabline_numbers=2

    nmap <D-1> <Plug>BufTabLine.Go(1)
    nmap <D-2> <Plug>BufTabLine.Go(2)
    nmap <D-3> <Plug>BufTabLine.Go(3)
    nmap <D-4> <Plug>BufTabLine.Go(4)
    nmap <D-5> <Plug>BufTabLine.Go(5)
    nmap <D-6> <Plug>BufTabLine.Go(6)
    nmap <D-7> <Plug>BufTabLine.Go(7)
    nmap <D-8> <Plug>BufTabLine.Go(8)
    nmap <D-9> <Plug>BufTabLine.Go(9)
endtry

syntax on

set gfn=Menlo\ Regular:h13
set hidden
set number

set laststatus=2
set noruler

set cmdheight=2
set noshowcmd

set wildmenu
set wildignore=*/.git/*,*/.svn/*
set wildignore+=*.o,*.so,*.pyc
set wildmode=longest:full

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab

set nowrapscan
set nowrap
set showmatch
set incsearch

set list
set listchars=tab:>-

set backspace=indent,eol,start

let g:netrw_liststyle = 3
let g:netrw_banner = 0

nmap <D-o> :Explore<CR>

" Auxiliary files and directories.

set viminfo+=n~/.vim/viminfo

if !isdirectory(expand('~/.vim/backup'))
    call mkdir(expand('~/.vim/backup'))
endif
set backupdir=~/.vim/backup//

if !isdirectory(expand('~/.vim/swap'))
    call mkdir(expand('~/.vim/swap'))
endif
set directory=~/.vim/swap//
set updatetime=1000

if !isdirectory(expand('~/.vim/undo'))
    call mkdir(expand('~/.vim/undo'))
endif
set undodir=~/.vim/undo//
set undofile

if &term == "screen-256color"
    autocmd BufEnter * call system("tmux rename-window " . "'vim:" . expand("%:t") . "'")
    autocmd VimLeave * call system("tmux setw automatic-rename")
endif

if filereadable(expand("~/.vim/vimrc-local"))
    source ~/.vim/vimrc-local
endif
