set nocompatible
set encoding=utf-8

if isdirectory(expand('~/.vim/bundle/Vundle.vim/'))
    filetype off

    set rtp+=~/.vim/bundle/Vundle.vim/
    call vundle#rc()

    Plugin 'gmarik/Vundle.vim'
    Plugin 'scrooloose/syntastic'
    Plugin 'bling/vim-bufferline'
    Plugin 'chriskempson/base16-vim'

    colorscheme base16-default
    set cursorline

    filetype plugin indent on

    autocmd VimEnter *
      \ let &statusline='%{bufferline#refresh_status()}' . '%=' . bufferline#get_status_string() . ' '
else
    colorscheme desert
endif

syntax on

let g:syntastic_mode_map = {'mode': 'active', 'passive_filetypes': ['tex']}
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_args = '--ignore=N801'

let g:bufferline_echo = 0

let g:bufferline_show_bufnr = 0
let g:bufferline_active_buffer_left = ''
let g:bufferline_active_buffer_right = ''

hi CustomActiveTab ctermbg=14
let g:bufferline_active_highlight = 'CustomActiveTab'
let g:bufferline_inactive_highlight = 'StatusLine'

set hidden

set number

set laststatus=2
set noruler

set cmdheight=2
set noshowcmd

set history=50

set wildignore=*/.git/*,*/.svn/*
set wildignore+=*.o,*.so,*.pyc
set wildmode=longest:full
set wildmenu

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab

set nowrapscan
set showmatch
set incsearch

set listchars=tab:>-
set list

set backspace=indent,eol,start


" Auxiliary files and directories.

set viminfo+=n~/.vim/viminfo

if !isdirectory(expand('~/.vim/backup'))
    call mkdir(expand('~/.vim/backup'))
endif
set backupdir=~/.vim/backup//

if !isdirectory(expand('~/.vim/swap'))
    call mkdir(expand('~/.vim/swap'))
endif
set directory=~/.vim/swap//
set updatetime=1000

if !isdirectory(expand('~/.vim/undo'))
    call mkdir(expand('~/.vim/undo'))
endif
set undodir=~/.vim/undo//
set undofile
