set nocompatible
set encoding=utf-8

if isdirectory(expand('~/.vim/bundle/Vundle.vim/'))
    filetype off

    set rtp+=~/.vim/bundle/Vundle.vim/
    call vundle#rc()

    Plugin 'gmarik/Vundle.vim'
    Plugin 'endel/vim-github-colorscheme'
    Plugin 'mihaifm/bufstop'

    filetype plugin indent on
endif

try
    colorscheme github
catch
    colorscheme desert
endtry

try
    nnoremap <Tab> :Bufstop<CR>
endtry
let g:BufstopKeys = "qwertyuiop"
let g:BufstopDismissKey = "<Tab>"

syntax on

set mouse=a
set gfn=Menlo\ Regular:h13
set hidden
set number

set laststatus=2
set noruler

set cmdheight=2
set noshowcmd

set wildmenu
set wildmode=longest:full
set wildignore=*/.git/*,*/.svn/*
set wildignore+=*.o,*.so,*.pyc

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab
set expandtab

set nowrapscan
set nowrap
set showmatch
set incsearch

set list
set listchars=tab:>-

set backspace=indent,eol,start

noremap <Up>    <NOP>
noremap <Down>  <NOP>
noremap <Left>  <NOP>
noremap <Right> <NOP>

noremap h       <NOP>
noremap j       <NOP>
noremap k       <NOP>
noremap l       <NOP>

noremap w       <NOP>
noremap b       <NOP>
noremap e       <NOP>
noremap ge      <NOP>
noremap W       <NOP>
noremap B       <NOP>
noremap E       <NOP>
noremap gE      <NOP>

noremap (       <NOP>
noremap )       <NOP>

noremap {       <NOP>
noremap }       <NOP>

" Auxiliary files and directories.

set viminfo+=n~/.vim/viminfo

if !isdirectory(expand('~/.vim/backup'))
    call mkdir(expand('~/.vim/backup'))
endif
set backupdir=~/.vim/backup//

if !isdirectory(expand('~/.vim/swap'))
    call mkdir(expand('~/.vim/swap'))
endif
set directory=~/.vim/swap//
set updatetime=1000

if !isdirectory(expand('~/.vim/undo'))
    call mkdir(expand('~/.vim/undo'))
endif
set undodir=~/.vim/undo//
set undofile

if &term == "screen-256color"
    autocmd BufEnter * call system("tmux rename-window " . "'vim:" . expand("%:t") . "'")
    autocmd VimLeave * call system("tmux setw automatic-rename")
endif

if filereadable(expand("~/.vim/vimrc-local"))
    source ~/.vim/vimrc-local
endif
