#!/usr/bin/env bash

echo "<openbox_pipe_menu>"
nmcli connection list \
    | tail -n +2 \
    | cut -f1 -d' ' \
    | while IFS= read -r network_id; do
          echo "<item label=\"${network_id}\">"
          echo "<action name=\"Execute\"><command>"
          echo "nmcli connection up id ${network_id}"
          echo "</command></action>"
          echo "</item>"
      done
echo "</openbox_pipe_menu>"
