# Hi, my name is Zach and I use Bash:)

# The goodies below are for interactive shells only.
if [ -z "$PS1" ]; then return; fi

# Let's begin from the end.
tput cup "$(tput lines)"

# That's my prompt.
PS1="\[\e[38;05;242m\](\A)\n\[\e[0m\]\$ "

# Don't you mess with it.
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Nobody will stand between Bash and ^S.
stty -ixon

# Those who cannot remember the past are condemned to repeat it.
shopt -s histappend
HISTSIZE=10000
HISTFILESIZE=10000

# Are there any other editors?
export EDITOR=vim

# Mere color, unspoiled by meaning, and unallied with definite form,
# can speak to the soul in a thousand different ways.
alias ls='ls --color=auto'

# Squeezing more out of less.
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Polyglot and proud of it:)
for xxenv in pyenv rbenv plenv; do
    xxenv_home="$HOME/.$xxenv/bin"

    export PATH+=":$xxenv_home"
    [ -x "$xxenv_home/$xxenv" ] && eval "$($xxenv init -)"
done

export PATH+=":$HOME/bin"

[ -f ~/.bashrc_private ] && source ~/.bashrc_private

# List tmux sessions.
if [ -x /usr/bin/tmux ] && [ -z "$TMUX" ] && tmux has-session 2> /dev/null; then
    echo '--- tmux sessions ---'
    tmux list-sessions -F '* #{session_name}'
fi
