# execute .profile
if [ -f ~/.profile ]; then
    source ~/.profile
fi

# execute .bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# invoke keychain on startup (but not on each tmux window)
if  [ -x /usr/bin/keychain ] && [ -z "$TMUX" ]; then
    eval $(keychain --eval ~/.ssh/id_rsa)
fi
